# Generated by Django 4.1.3 on 2022-11-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('company', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'referrer',
            },
        ),
    ]
