# Generated by Django 4.1.2 on 2022-11-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referrer_linkedin_referrer_role_referrer_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer',
            name='linkedin',
            field=models.URLField(default='https://linkedin.com/', max_length=150),
        ),
        migrations.AlterModelTable(
            name='referrer',
            table=None,
        ),
    ]
